import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import AuthProvider from "@/app/Context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Budget Tracker",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <AuthProvider>{children}</AuthProvider>
                </LocalizationProvider>
            </body>
        </html>
    );
}
