"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";

import MiniDrawer from "./Components/UI/Nav";
import Providers from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <LocalizationProvider dateAdapter={AdapterDayjs}>
                        <MiniDrawer />
                        {children}
                    </LocalizationProvider>
                </Providers>
            </body>
        </html>
    );
}
